FROM python:3.7.6
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app/
RUN pip install -r requirements.txt
COPY ./app/get_python_from_html.py /app/get_python_from_html.py
ENTRYPOINT celery -A get_python_from_html worker --loglevel=info