FROM python:3.7.6
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt
COPY ./app/app.py /app/app.py
COPY ./app/models.py /app/models.py
RUN mkdir /app/templates
COPY ./app/templates/index.html /app/templates/index.html
ENTRYPOINT ["python"]
CMD ["app.py"]